name: TEST

on:
  push:
    branches:
      - master

jobs:
  notify_on_telegram:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify the commit on Telegram
      uses: EverythingSuckz/github-telegram-notify@main
      with:
        bot_token: 6326105153:AAFk5bfjbgSI_Q71efXd7bd3X7bCi0QiB94
        chat_id: -4065887641
